### ISSUE TITLE
这个一直卡在初始界面进不去啥情况

### ISSUE THREAD

**Issue by DucanEdwards** [modifyFun/Weather_forecast_App#1]

**Comment by modifyFun** [comment]
需要到和风天气申请一个有七天天气预报的访问权限的 key，然后在 tq\app\src\main\java\com\xianguoliang\tools\MyApp.java 文件下的 HEKEY 变量，赋值你申请的和风天气接口Key

**Comment by DucanEdwards** [comment]
已经把key填进去了 但是就授权后一直卡在初始界面一直加载

**Comment by modifyFun** [comment]
需要申请类型为web api 的key，并且要实名认证后获得七天天气预报的访问权限

**Comment by DucanEdwards** [comment]
hh貌似不是和风天气key的问题 刚才调试了另一个开源项目，可以获取天气数据 但这个项目还是进不去

**Comment by modifyFun** [comment]
获取的数据发一下看看，如果是三天的话是进不去的，我这边打开是正常的

**Comment by DucanEdwards** [comment]
xd给个联系方式

**Comment by DucanEdwards** [comment]
急 有空的话请求远程解决一下

**Comment by modifyFun** [comment]
qq 976066353

**Comment by zgz-alt** [comment]
同问
